### ISSUE TITLE
__init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-attachment#97]
Setting up kinto-attachment 0.7.0 locally against Kinto 3.2.1, Ubuntu 16.05, Python 3.5.1 (standard dist package).

`kinto.ini`:

```ini
[app:main]
use = egg:kinto

# Required by integration tests
kinto.flush_endpoint_enabled = true

# Required by basic auth
kinto.userid_hmac_secret = a-secret-string

# Allow browsing all buckets
kinto.bucket_read_principals = system.Authenticated

# Plugins registration
kinto.includes = kinto.plugins.default_bucket
                 kinto_attachment

# Kinto-attachment
kinto.attachment.base_url = http://cdn.service.org/files/
kinto.attachment.folder = {bucket_id}/{collection_id}
kinto.attachment.keep_old_files = true
kinto.attachment.base_path = /tmp

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 8888
```

The server starts fine:

```
$ .venv/bin/kinto --ini test/kinto.ini start
Starting server in PID 7954.
serving on http://0.0.0.0:8888
```

But requesting `GET http://0.0.0.0:8888/v1/buckets/custom/collections/plop/records/96a38b32-2bf2-47a2-9ddc-944965ebd6dd/attachment` explodes with:

```
ERROR:kinto.core.views.errors:"GET   /v1/buckets/custom/collections/plop/records/96a38b32-2bf2-47a2-9ddc-944965ebd6dd/attachment" ? (? ms) __init__() takes 2 positional arguments but 3 were given agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 authn_type=None errno=None exception=Traceback (most recent call last):
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid/router.py", line 127, in handle_request
    root = root_factory(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/kinto_attachment/utils.py", line 32, in __init__
    resource = Record(request, self)
TypeError: __init__() takes 2 positional arguments but 3 were given lang=fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4 uid=None
```

What am I doing wrong? Edit: I know this GET request is not supported, though I was not expecting it to raise.

**Comment by n1k0** [comment]
It does the some for a POST request on the same endpoint.

**Comment by Natim** [comment]
I could reproduce here.

**Comment by Natim** [comment]
Trying to go back to the previous release to see if it fixes the matter.

**Comment by leplatrem** [comment]
The constructor or `Record` was changed in 3.2.1 from `def __init__(self, *args, **kwargs):` to this `def __init__(self, request, **kwargs):`

**Comment by Natim** [comment]
Yes :) I am adding a fix and a test.
